negation_words:
  - not
  - no
  - none
  - neither
  - never
  - nobody
  - nothing
  - nowhere
  - cannot
  - isn't
  - aren't
  - wasn't
  - weren't
  - haven't
  - hasn't
  - hadn't
  - doesn't
  - don't
  - didn't
  - won't
  - wouldnt
  - shan't
  - shouldnt
  - can't
  - cannot
  - couldn't
  - mustn't